from py2neo import Graph, Node, Relationship

graph = Graph(auth=('neo4j', 'Neo4j'))    #http://localhost:7474

graph.delete_all()

Node('IfcPerson', nid=1, FamilyName="\u672a\u5b9a\u7fa9")
Node('IfcOrganization', nid=3, Name="\u672a\u5b9a\u7fa9")
Node('IfcPersonAndOrganization', nid=7)
Node('IfcOrganization', nid=10, Id="GS", Description="GRAPHISOFT", Name="GRAPHISOFT")
Node('IfcApplication', nid=11, ApplicationId=tifier="IFC add-on version=5009 JPN FULL", Version="22.0.0", ApplicationFullName="ARCHICAD-64")
Node('IfcOwnerHistory', nid=12, ChangeAction="ADDED")
Node('IfcSIUnit', nid=13, UnitType="LENGTHUNIT", Name="METRE", Prefix="MILLI")
Node('IfcSIUnit', nid=14, UnitType="AREAUNIT", Name="SQUARE_METRE")
Node('IfcSIUnit', nid=15, UnitType="VOLUMEUNIT", Name="CUBIC_METRE")
Node('IfcSIUnit', nid=16, UnitType="PLANEANGLEUNIT", Name="RADIAN")
Node('IfcMeasureWithUnit', nid=17)
Node('IfcDimensionalExponents', nid=18)
Node('IfcConversionBasedUnit', nid=19, UnitType="PLANEANGLEUNIT", Name="DEGREE")
Node('IfcSIUnit', nid=20, UnitType="SOLIDANGLEUNIT", Name="STERADIAN")
Node('IfcMonetaryUnit', nid=21, Currency="JPY")
Node('IfcSIUnit', nid=22, UnitType="TIMEUNIT", Name="SECOND")
Node('IfcMeasureWithUnit', nid=23)
Node('IfcDimensionalExponents', nid=24)
Node('IfcConversionBasedUnit', nid=25, UnitType="TIMEUNIT", Name="Year")
Node('IfcSIUnit', nid=26, UnitType="MASSUNIT", Name="GRAM", Prefix="KILO")
Node('IfcSIUnit', nid=27, UnitType="THERMODYNAMICTEMPERATUREUNIT", Name="DEGREE_CELSIUS")
Node('IfcSIUnit', nid=28, UnitType="LUMINOUSINTENSITYUNIT", Name="LUMEN")
Node('IfcSIUnit', nid=29, UnitType="ENERGYUNIT", Name="JOULE", Prefix="MEGA")
Node('IfcDerivedUnit', nid=30, UnitType="THERMALCONDUCTANCEUNIT")
Node('IfcSIUnit', nid=32, UnitType="POWERUNIT", Name="WATT")
Node('IfcDerivedUnitElement', nid=33)
Node('IfcSIUnit', nid=34, UnitType="LENGTHUNIT", Name="METRE")
Node('IfcDerivedUnitElement', nid=35)
Node('IfcSIUnit', nid=36, UnitType="THERMODYNAMICTEMPERATUREUNIT", Name="KELVIN")
Node('IfcDerivedUnitElement', nid=37)
Node('IfcDerivedUnit', nid=38, UnitType="SPECIFICHEATCAPACITYUNIT")
Node('IfcSIUnit', nid=40, UnitType="ENERGYUNIT", Name="JOULE")
Node('IfcDerivedUnitElement', nid=41)
Node('IfcSIUnit', nid=42, UnitType="MASSUNIT", Name="GRAM", Prefix="KILO")
Node('IfcDerivedUnitElement', nid=43)
Node('IfcSIUnit', nid=44, UnitType="THERMODYNAMICTEMPERATUREUNIT", Name="KELVIN")
Node('IfcDerivedUnitElement', nid=45)
Node('IfcDerivedUnit', nid=46, UnitType="MASSDENSITYUNIT")
Node('IfcSIUnit', nid=48, UnitType="MASSUNIT", Name="GRAM", Prefix="KILO")
Node('IfcDerivedUnitElement', nid=49)
Node('IfcSIUnit', nid=50, UnitType="VOLUMEUNIT", Name="CUBIC_METRE")
Node('IfcDerivedUnitElement', nid=51)
Node('IfcUnitAssignment', nid=52)
Node('IfcDirection', nid=54)
Node('IfcDirection', nid=58)
Node('IfcCartesianPoint', nid=60)
Node('IfcAxis2Placement3D', nid=62)
Node('IfcDirection', nid=63)
Node('IfcGeometricRepresentationContext', nid=65, ContextType="Model", Precision=1e-05)
Node('IfcProject', nid=68, Name="TE\u30d3\u30eb\u3007\u3007\u8a08\u753b", GlobalId="344O7vICcwH8qAEnwJDjSU")
Node('IfcDirection', nid=75)
Node('IfcDirection', nid=77)
Node('IfcCartesianPoint', nid=79)
Node('IfcAxis2Placement3D', nid=81)
Node('IfcLocalPlacement', nid=82)
Node('IfcSite', nid=85, CompositionType="ELEMENT", RefElevation=0.0, Description="TK\u30c6\u30f3\u30d7\u30ec\u30fc\u30c821_03", GlobalId="20FpTZCqJy2vhVJYtjuIce", Name="\u30b5\u30a4\u30c8")
Node('IfcRelAggregates', nid=91, GlobalId="0Du7$nzQXCktKlPUTLFSAT")
Node('IfcQuantityLength', nid=97, LengthValue=0.0, Name="GrossPerimeter")
Node('IfcQuantityArea', nid=99, AreaValue=0.0, Name="GrossArea")
Node('IfcElementQuantity', nid=100, MethodOfMeasurement="ARCHICAD BIM Base Quantities", Name="BaseQuantities", GlobalId="2GNZepdf73fvGc$0W6rozj")
Node('IfcRelDefinesByProperties', nid=105, GlobalId="2Hm9JvZjohDNSD2kdxZI3b")
Node('IfcDirection', nid=109)
Node('IfcDirection', nid=111)
Node('IfcCartesianPoint', nid=113)
Node('IfcAxis2Placement3D', nid=115)
Node('IfcLocalPlacement', nid=116)
Node('IfcBuilding', nid=118, CompositionType="ELEMENT", GlobalId="00tMo7QcxqWdIGvc4sMN2A", Name="\u5efa\u7bc9")
Node('IfcRelAggregates', nid=120, GlobalId="2b_h_mYcGArd6glJG2Fmbt")
Node('IfcQuantityArea', nid=124, AreaValue=4942.73006402, Name="GrossFloorArea")
Node('IfcElementQuantity', nid=125, MethodOfMeasurement="ARCHICAD BIM Base Quantities", Name="BaseQuantities", GlobalId="1kQMlmT0rD35a9E43iKTas")
Node('IfcRelDefinesByProperties', nid=127, GlobalId="0L87OdSD3DqSTjSRlAciZL")
Node('IfcDirection', nid=131)
Node('IfcDirection', nid=133)
Node('IfcCartesianPoint', nid=135)
Node('IfcAxis2Placement3D', nid=137)
Node('IfcLocalPlacement', nid=138)
Node('IfcBuildingStorey', nid=140, CompositionType="ELEMENT", Elevation=-1550.0, GlobalId="3j1csCqCP9tuK0Cjxh2tQP", Name="\u30d4\u30c3\u30c8")
Node('IfcRelAggregates', nid=142, GlobalId="118jwqMnuwK1xuf97w7fU5")
Node('IfcQuantityLength', nid=146, LengthValue=1409.0, Name="NetHeight")
Node('IfcQuantityLength', nid=147, LengthValue=1409.0, Name="GrossHeight")
Node('IfcQuantityLength', nid=148, LengthValue=1409.0, Name="Height")
Node('IfcQuantityArea', nid=149, AreaValue=18.195, Name="GrossFloorArea")
Node('IfcElementQuantity', nid=150, MethodOfMeasurement="ARCHICAD BIM Base Quantities", Name="BaseQuantities", GlobalId="2TYi754eT$HKFPaw5AIqFf")
Node('IfcRelDefinesByProperties', nid=152, GlobalId="2X85BO50S5bhIEiZIJaLWq")
Node('IfcDirection', nid=156)
Node('IfcDirection', nid=158)
Node('IfcCartesianPoint', nid=160)
Node('IfcAxis2Placement3D', nid=162)
Node('IfcLocalPlacement', nid=163)
Node('IfcGeometricRepresentationSubContext', nid=165, ContextType="Model", TargetView="MODEL_VIEW", ContextIdentifier="Body")
Node('IfcCartesianPoint', nid=167)
Node('IfcCartesianPoint', nid=169)
Node('IfcCartesianPoint', nid=171)
Node('IfcCartesianPoint', nid=173)
Node('IfcPolyLoop', nid=175)
Node('IfcFaceOuterBound', nid=177, Orientation=true)
Node('IfcFace', nid=178)
Node('IfcCartesianPoint', nid=180)
Node('IfcCartesianPoint', nid=182)
Node('IfcPolyLoop', nid=184);Node('IfcFaceOuterBound', nid=186, Orientation=true)
Node('IfcFace', nid=187)
Node('IfcCartesianPoint', nid=189)
Node('IfcPolyLoop', nid=191)
Node('IfcFaceOuterBound', nid=193, Orientation=true)
Node('IfcFace', nid=194)
Node('IfcCartesianPoint', nid=196)
Node('IfcPolyLoop', nid=198)
Node('IfcFaceOuterBound', nid=200, Orientation=true)
Node('IfcFace', nid=201)
Node('IfcPolyLoop', nid=203)
Node('IfcFaceOuterBound', nid=205, Orientation=true)
Node('IfcFace', nid=206)
Node('IfcPolyLoop', nid=208)
Node('IfcFaceOuterBound', nid=210, Orientation=true)
Node('IfcFace', nid=211)
Node('IfcClosedShell', nid=213)
Node('IfcFacetedBrep', nid=215)
Node('IfcColourRgb', nid=216, Red=1.0, Green=0.603921568627, Blue=1.0)
Node('IfcSurfaceStyleRendering', nid=217, Transparency=0.5, ReflectanceMethod="NOTDEFINED")
Node('IfcSurfaceStyle', nid=218, Name="\u25a0\u5206\u985e\uff11", Side="BOTH")
Node('IfcPresentationStyleAssignment', nid=220)
Node('IfcStyledItem', nid=222)
Node('IfcShapeRepresentation', nid=225, RepresentationId=tifier="Body", RepresentationType="Brep")
Node('IfcPresentationLayerAssignment', nid=232, Name="M810_\u30be\u30fc\u30f3")
Node('IfcGeometricRepresentationSubContext', nid=235, ContextType="Model", TargetView="MODEL_VIEW", ContextIdentifier="FootPrint")
Node('IfcCartesianPoint', nid=236)
Node('IfcCartesianPoint', nid=238)
Node('IfcCartesianPoint', nid=240)
Node('IfcCartesianPoint', nid=242)
Node('IfcPolyline', nid=244)
Node('IfcGeometricCurveSet', nid=246)
Node('IfcShapeRepresentation', nid=248, RepresentationId=tifier="FootPrint", RepresentationType="GeometricCurveSet")
Node('IfcProductDefinitionShape', nid=251)
Node('IfcSpace', nid=257, InteriorOrExteriorSpace="INTERNAL", CompositionType="ELEMENT", LongName="9867", GlobalId="2tfCrredj3qgTRPcdysXJV", Name="\u6d88\u706b\u6c34\u69fd")
Node('IfcRelAggregates', nid=262, GlobalId="0sjoJ2gqMY075CDlEMdbW0")
Node('IfcPropertySingleValue', nid=266, Name="Category", NominalValue="\u5171\u7528")
Node('IfcPropertySet', nid=270, Name="Pset_SpaceCommon", GlobalId="0UlaVwHFhdLoTPDCAKOpQ4")
Node('IfcRelDefinesByProperties', nid=272, GlobalId="0cqGvs1krL856fPAKtJ_Zi")
Node('IfcPropertySingleValue', nid=276, Name="Baseboard", NominalValue="-")
Node('IfcPropertySingleValue', nid=277, Name="BaseboardHeight", NominalValue="0.00")
Node('IfcPropertySingleValue', nid=278, Name="BaseboardSubstrate", NominalValue="-")
Node('IfcPropertySingleValue', nid=279, Name="BeamShapeApproved number", NominalValue="-")
Node('IfcPropertySingleValue', nid=280, Name="BeamShapeCovering", NominalValue="-")
Node('IfcPropertySingleValue', nid=281, Name="BeamShapeSubstrate", NominalValue="-")
Node('IfcPropertySingleValue', nid=282, Name="CeilingApprovedNumber", NominalValue="-")
Node('IfcPropertySingleValue', nid=283, Name="CeilingCovering", NominalValue="-")
Node('IfcPropertySingleValue', nid=284, Name="CeilingHeight", NominalValue="0.00")
Node('IfcPropertySingleValue', nid=285, Name="CeilingSubstrate", NominalValue="-")
Node('IfcPropertySingleValue', nid=286, Name="CrownMolding", NominalValue="-")
Node('IfcPropertySingleValue', nid=287, Name="FloorCovering", NominalValue="-")
Node('IfcPropertySingleValue', nid=288, Name="FloorHeight", NominalValue="0.00")
Node('IfcPropertySingleValue', nid=289, Name="FroorSubstrate", NominalValue="-")
Node('IfcPropertySingleValue', nid=290, Name="FroorWaterproofing", NominalValue="")
Node('IfcPropertySingleValue', nid=291, Name="Other", NominalValue="\u672a\u5b9a\u7fa9")

##############################################################

# tx = graph.begin()

# a = Node("Person", name="Alice")

# tx.create(a)

# b = Node("Person", name="Bob")
# ab = Relationship(a, "KNOWS", b)

# tx.create(ab)
# tx.commit()
# print(graph.exists(ab))

##############################################################

# nicole = Node("Person", name="Nicole", age=24)
# drew = Node("Person", name="Drew", age=20)

# mtdew = Node("Drink", name="Mountain Dew", calories=9000)
# cokezero = Node("Drink", name="Coke Zero", calories=0)

# coke = Node("Manufacturer", name="Coca Cola")
# pepsi = Node("Manufacturer", name="Pepsi")

# graph.create(nicole | drew | mtdew | cokezero | coke | pepsi)

# graph.create(Relationship(nicole, "LIKES", cokezero))
# graph.create(Relationship(nicole, "LIKES", mtdew))
# graph.create(Relationship(drew, "LIKES", mtdew))
# graph.create(Relationship(coke, "MAKES", cokezero))
# graph.create(Relationship(pepsi, "MAKES", mtdew))

